#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


# Boot picom or compton if it exists
picom --config ~/.config/picom.conf &> /dev/null &

# EasyEffects for pipewire
easyeffects --gapplication-service &

# auto lock with slock
xss-lock -- slock &

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"


# Set background
if [ -x "$(command -v feh)" ]; then
  feh --bg-scale $SCRIPTPATH/maybe-transformed.jpeg
fi

# Conky
#~/.config/conky/start-conky.sh

# index=0
# monitor="$(polybar -m | grep +0+0 | sed s/:.*// | tac)"
# leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
# do
#  barname="bar"
#  monitor=$monitor offsetx=$x width=$width polybar -c $SCRIPTPATH/polybar/config.ini -r $barname &>> ~/.local/var/log/polybar-$monitor.log &
#done

if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar -c $SCRIPTPATH/polybar/config.ini --reload bar &>> ~/.local/var/log/polybar-$monitor.log &
  done
else
  polybar -c $SCRIPTPATH/polybar/config.ini --reload bar &>> ~/.local/var/log/polybar.log &
fi
